[project]
name = "motivate-me"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.25",
    "langchain-mistralai>=0.2.10",
    "langgraph>=0.4.7",
]
